# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('add_text', models.TextField()),
                ('photo', models.ImageField(upload_to='exp')),
            ],
        ),
    ]
