# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_exposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='exp.png', upload_to='exp'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='photo',
            field=models.ImageField(default='exp.png', upload_to='exp'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
