# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20190302_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
