# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20190302_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='photo_alt',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='exposition',
            name='photo_title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_alt',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='add_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='news.png', upload_to='news'),
        ),
    ]
