# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_auto_20190321_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('copy', models.NullBooleanField()),
            ],
        ),
    ]
