# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='exp.png', upload_to='exp')),
                ('imf_alt', models.CharField(default='none', max_length=200)),
                ('img_title', models.CharField(default='none', max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Exposition')),
            ],
        ),
        migrations.CreateModel(
            name='Post_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='news.png', upload_to='news')),
                ('imf_alt', models.CharField(default='none', max_length=200)),
                ('img_title', models.CharField(default='none', max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Post')),
            ],
        ),
    ]
