# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_exposition_img_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposition_img',
            name='imf_alt',
        ),
        migrations.RemoveField(
            model_name='post_img',
            name='imf_alt',
        ),
        migrations.AddField(
            model_name='exposition_img',
            name='img_alt',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AddField(
            model_name='post_img',
            name='img_alt',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='add_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='photo',
            field=models.ImageField(default='exp.png', upload_to='exp', verbose_name='Превью фото'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='photo_alt',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='photo_title',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото при наведении'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подназвание'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название экспозиции'),
        ),
        migrations.AlterField(
            model_name='exposition_img',
            name='img',
            field=models.ImageField(default='exp.png', upload_to='exp', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='exposition_img',
            name='img_title',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото при наведении'),
        ),
        migrations.AlterField(
            model_name='exposition_img',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Exposition', verbose_name='Экспозиция'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=100, verbose_name='Имя отпрвителя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='news.png', upload_to='news', verbose_name='Превью фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_alt',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_title',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото при наведении'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=models.TextField(default='none', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img',
            field=models.ImageField(default='news.png', upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='img_title',
            field=models.CharField(default='none', max_length=200, verbose_name='Описание фото при наведении'),
        ),
        migrations.AlterField(
            model_name='post_img',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Post', verbose_name='Новость'),
        ),
    ]
