# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_auto_20190331_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposition_img',
            old_name='post',
            new_name='exp',
        ),
    ]
